version: "3"
networks:
  sae.net:
    driver: bridge

services:
  api:
    image: stanislasj/sae_php:latest
    environment:
      - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
      - https_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
    ports:
      - "18096:80"
    volumes:
      - ./MiniPress.core/api/public:/var/www/html
      - ./MiniPress.core/api/src:/var/www/src
    working_dir: /var/www/src
    networks:
      - sae.net
    depends_on:
      - sql

  appli:
    image: stanislasj/sae_php:latest
    environment:
      - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
      - https_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
    ports:
      - "18095:80"
    volumes:
      - ./MiniPress.core/appli/public:/var/www/html
      - ./MiniPress.core/appli/src:/var/www/src
    working_dir: /var/www/src
    networks:
      - sae.net
    depends_on:
      - sql
    
  webjs:
    image: stanislasj/sae_php:latest
    environment:
      - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
      - https_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
    ports:
      - "18095:80"
    volumes:
      - ./MiniPress.web:/var/www/html
    working_dir: /var/www/html
    networks:
      - sae.net
    depends_on:
      - sql
      - api

  sql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER_NAME}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
    ports:
      - "18098:3306"
    networks:
      sae.net:
        aliases:
          - sql.db

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: sql
      PMA_PORT: 3306
    ports:
      - "18097:80"
    networks:
      - sae.net
    depends_on:
      - sql