version: "1"
networks:
  giftbox.net:
    driver: bridge

services:
  api:
    image: stanislasj/sae_php:latest
    environment:
      - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
      - https_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
    ports:
      - "18085:80"
    volumes:
      - ./MiniPress.core/api/public:/var/www/html
      - ./MiniPress.core/api/src:/var/www/src
    working_dir: /var/www/src
    networks:
      - giftbox.net
    depends_on:
      - sql

  appli:
    image: stanislasj/sae_php:latest
    environment:
      - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
      - https_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
    ports:
      - "18086:80"
    volumes:
      - ./MiniPress.core/appli/public:/var/www/html
      - ./MiniPress.core/appli/src:/var/www/src
    working_dir: /var/www/src
    networks:
      - giftbox.net
    depends_on:
      - sql

  sql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER_NAME}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
    ports:
      - "18088:3306"
    networks:
      giftbox.net:
        aliases:
          - sql.db

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: sql
      PMA_PORT: 3306
    ports:
      - "18087:80"
    networks:
      - giftbox.net